### PR TITLE
fix gsn-10917: fix event driven suppressing

### PR DESCRIPTION
**Pull request by carlovoSBP**

### CODE REVIEW

**Review by costastf — COMMENTED** [review]
I am not a huge fan of "resource_id_regex_list" tbh. I think it also looks pretty bad in the rule definition. I would prefer that without the type suffix like :"resource_id_regexps" or something to the effect. my 2c.

**Comment by carlovoSBP** [comment]
> I am not a huge fan of "resource_id_regex_list" tbh. I think it also looks pretty bad in the rule definition. I would prefer that without the type suffix like :"resource_id_regexps" or something to the effect. my 2c.

Yes, that seems better. Are you okay with `rule_or_control_id` and the re-wording in general?

Little background, I was getting frustrated by the mental strain of translating the terms in the lib to the keywords that actually matter to Security Hub all the time while developing. Also, I think both current terms are slightly misleading to users. So, I would like to change them, but I'm all up for better suggestions.

**Comment by costastf** [comment]
Yeah, apart from the type suffix, all else is fine as it corresponds to the domain correctly.

**Review by costastf — APPROVED** [review]
Looks good! I really like the `match_if_set` touch!

**Pull request merged**
